Update passmenu-otp

diff --git a/passmenu-otp b/passmenu-otp
--- a/passmenu-otp
+++ b/passmenu-otp
@@ -8,12 +8,23 @@ if [[ $1 == "--type" ]]; then
 	shift
 fi
 
+if [[ -n $WAYLAND_DISPLAY ]]; then
+	dmenu="/usr/bin/wofi --dmenu"
+	xdotool="ydotool type --file -"
+elif [[ -n $DISPLAY ]]; then
+	dmenu=dmenu
+	xdotool="xdotool type --clearmodifiers --file -"
+else
+	echo "Error: No Wayland or X11 display detected" >&2
+	exit 1
+fi
+
 prefix=${PASSWORD_STORE_DIR-~/.password-store}
 password_files=( "$prefix"/**/*.gpg )
 password_files=( "${password_files[@]#"$prefix"/}" )
 password_files=( "${password_files[@]%.gpg}" )
 
-password=$(printf '%s\n' "${password_files[@]}" | dmenu "$@")
+password=$(printf '%s\n' "${password_files[@]}" | $dmenu "$@")
 
 [[ -n $password ]] || exit
 
@@ -23,8 +34,7 @@ if pass show "$password" | grep -q '^otpauth://'; then
 fi
 
 if [[ $typeit -eq 0 ]]; then
-	pass $pass_cmd -c "$password" 2>/dev/null
+	pass $pass_cmd  -c "$password" 2>/dev/null
 else
-	pass $pass_cmd "$password" | { IFS= read -r pass; printf %s "$pass"; } |
-		xdotool type --clearmodifiers --file -
+	pass $pass_cmd  "$password" | { IFS= read -r pass; printf %s "$pass"; } | $xdotool
 fi
